CREATE DATABASE PET_FRIENDS;

USE PET_FRIENDS;

CREATE TABLE DONO_PET (
	ID_DONO INT NOT NULL AUTO_INCREMENT,
    DONO_NOME VARCHAR(45) NOT NULL,
    DONO_SOBRENOME VARCHAR(100) NOT NULL,
    DONO_CPF VARCHAR(12),
    DONO_ENDERECO VARCHAR(100),
    DONO_EMAIL VARCHAR(45),
    DONO_TELEFONE VARCHAR(15) NOT NULL,
    PRIMARY KEY(ID_DONO)
    );
      
CREATE TABLE PET (
	ID_PET INT NOT NULL AUTO_INCREMENT,
    ID_DONO INT NOT NULL,
    PET_NOME VARCHAR(45) NOT NULL,
    PET_GENERO VARCHAR(1) NOT NULL,
    PET_TIPO VARCHAR (45),
    PET_RACA VARCHAR(45),
    PET_PESO DECIMAL(5,2),
    PRIMARY KEY(ID_PET),
    CONSTRAINT FK_PET_DONO FOREIGN KEY (ID_DONO) REFERENCES DONO_PET (ID_DONO)
    );
 
 CREATE TABLE VETERINARIO (
	ID_VETERINARIO INT NOT NULL AUTO_INCREMENT,
	VETERINARIO_NOME VARCHAR(45) NOT NULL,
    VETERINARIO_ESPECIALIDADE VARCHAR(100),
    PRIMARY KEY(ID_VETERINARIO)
	);
    
CREATE TABLE EXAME (
	ID_EXAME INT NOT NULL AUTO_INCREMENT,
    EXAME_NOME VARCHAR(100),
    PRIMARY KEY(ID_EXAME)
    );
      
CREATE TABLE CONSULTA (
	ID_CONSULTA INT NOT NULL AUTO_INCREMENT,
    ID_PET INT NOT NULL,
    ID_VETERINARIO INT NOT NULL,
    ID_EXAME INT NOT NULL,
    CONSULTA_DATA DATE,
    CONSULTA_HORA TIME,
    PRIMARY KEY(ID_CONSULTA),
    CONSTRAINT FK_CONSULTA_PET FOREIGN KEY (ID_PET) REFERENCES PET (ID_PET),
    CONSTRAINT FK_CONSULTA_VETERINARIO FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO (ID_VETERINARIO),
    CONSTRAINT FK_CONSULTA_EXAME FOREIGN KEY (ID_EXAME) REFERENCES EXAME (ID_EXAME)
    );

